changelog:
  categories:
    - title: "Breaking Changes"
      labels:
        - "breaking-change"
        - "breaking"
    - title: "Features"
      labels:
        - "feature"
        - "enhancement"
    - title: "Bug Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "Documentation"
      labels:
        - "docs"
        - "documentation"
    - title: "Maintenance"
      labels:
        - "chore"
        - "ci"
        - "refactor"
        - "build"
  exclude:
    labels:
      - "skip-changelog"

