name: Bug report
description: Report a reproducible problem in StoryTime
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.
        Please include as much detail as possible so we can reproduce the issue.

  - type: dropdown
    id: area
    attributes:
      label: Area
      multiple: true
      options:
        - Backend (Spring Boot)
        - Frontend (Thymeleaf / static assets)
        - Database (PostgreSQL)
        - Demo mode
        - Docs
        - CI
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version / commit
      description: Tag, branch, or commit SHA.
      placeholder: e.g. main @ abc1234
    validations:
      required: false

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Include the exact commands and inputs.
      placeholder: |
        1. docker compose up -d
        2. ./gradlew bootRun --args='--spring.profiles.active=demo'
        3. Open http://localhost:8080/education
        4. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      description: Paste relevant logs (redact secrets), or attach screenshots.
      render: shell
    validations:
      required: false

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, Java version, Docker version (if applicable).
      placeholder: e.g. macOS 14, Java 17, Docker Desktop 4.x
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues
          required: true
        - label: I have removed any secrets from logs/screenshots
          required: true

