name: Feature request
description: Suggest an idea or enhancement for StoryTime
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing an improvement!
        For larger changes, consider opening a discussion first (or a draft PR).

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see implemented?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
    validations:
      required: false

  - type: textarea
    id: scope
    attributes:
      label: Scope / acceptance criteria
      placeholder: |
        - [ ] ...
        - [ ] ...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have checked the README and existing issues/PRs
          required: true

